import { Chapter } from "../types";

export const chapters: Chapter[] = [
  {
    id: 1,
    number: 1,
    title: "Arrays",
    slug: "arrays",
    description:
      "The foundation of everything. You already use arrays daily — now learn to think about them algorithmically.",
    webDevConnection:
      "Every time you render a list in React, you're iterating an array. Optimizing that iteration is optimizing your app.",
    problemCount: 28,
    status: "active",
    jsBridgeTopics: [
      "Array indexing and bounds (what happens at arr[-1] and arr[arr.length])",
      "The difference between arr.length and last valid index",
      "In-place mutation vs. returning a new array (.splice vs. spread)",
      "Two-pointer pattern using index variables (not .indexOf)",
      "Prefix sum concept using a plain for loop",
    ],
    coreConcepts: [
      "Array traversal patterns: single pass, two pointers, sliding window",
      "In-place operations and why they matter for memory",
      "Subarray problems and the prefix sum trick",
      "When arrays beat every other data structure (and when they don't)",
      "Big-O for common operations: access O(1), search O(n), insert/delete O(n)",
    ],
  },
  {
    id: 2,
    number: 2,
    title: "Linear Search",
    slug: "linear-search",
    description:
      "Deceptively simple. Think about what 'search' means algorithmically and establish the baseline for why better algorithms exist.",
    webDevConnection:
      "You linear search every time you do users.find(u => u.id === targetId). It's fine for 50 users. What about 50,000?",
    problemCount: 16,
    status: "locked",
    jsBridgeTopics: [
      "How Array.prototype.find() works under the hood (it's a linear search)",
      "for vs. while loops for search — when to use each",
      "Early exit with return (or break) — why it matters",
      "Searching objects in arrays by property value",
    ],
    coreConcepts: [
      "Sequential scan: visiting every element until found or exhausted",
      "Best case O(1), worst case O(n), average O(n/2) → O(n)",
      "When linear search is actually the right choice (small arrays, unsorted data, single search)",
      "Sentinel values — the trick to avoid a bounds check every iteration",
    ],
  },
  {
    id: 3,
    number: 3,
    title: "Binary Search",
    slug: "binary-search",
    description:
      "The first algorithm that genuinely surprises people. Deep pattern recognition — not just the textbook version, but every disguised form.",
    webDevConnection:
      "Autocomplete dropdowns, range filters, and paginated sorted lists all use binary search patterns.",
    problemCount: 22,
    status: "locked",
    jsBridgeTopics: [
      "Math.floor() and integer midpoint calculation (why (lo + hi) >> 1 prevents overflow)",
      "While loops with two moving boundaries",
      "The off-by-one trap: when to use lo < hi vs. lo <= hi",
      "Sorting prerequisite: always confirm the array is sorted before applying",
    ],
    coreConcepts: [
      "The invariant: the answer is always inside [lo, hi]",
      "Three flavors: exact match, leftmost occurrence, rightmost occurrence",
      "Binary search on the answer space (not just on an array)",
      "Complexity: O(log n) — 'how many times can you halve 1 billion?'",
    ],
  },
  {
    id: 4,
    number: 4,
    title: "Sorting",
    slug: "sorting",
    description:
      "All 8 sorting algorithms in strict order. Each unlocks a new mental model. This is where intuition for algorithmic thinking is built.",
    webDevConnection:
      "JavaScript's Array.prototype.sort() uses TimSort (merge + insertion). Now you know exactly what's happening.",
    problemCount: 32,
    status: "locked",
    jsBridgeTopics: [
      "Nested for loops and swapping variables",
      "array.splice(), shifting elements, the 'sorted portion' invariant",
      "array.slice(), spreading arrays, recursive function calls",
      "Partitioning with in-place swaps, pivot selection",
      "Arrays as trees (parent at i, children at 2i+1 and 2i+2)",
      "Creating arrays of arrays, Math.floor for bucketing",
      "Modulo and division for digit extraction",
      "Using an array as a frequency map (index = value)",
    ],
    coreConcepts: [
      "Bubble Sort → adjacent comparisons, passes, early-exit",
      "Insertion Sort → building sorted prefix one element at a time",
      "Merge Sort → divide-and-conquer, the merge step",
      "Quick Sort → Lomuto vs. Hoare partition, pivot choice",
      "Heap Sort → max-heap in-place, heapify operation",
      "Bucket Sort → distributing into buckets by range",
      "Radix Sort → digit-by-digit, LSD to MSD",
      "Counting Sort → frequency map, cumulative counts",
    ],
  },
  {
    id: 5,
    number: 5,
    title: "HashMap",
    slug: "hashmap",
    description:
      "The single most powerful tool for turning O(n²) brute force into O(n) elegance. This chapter should feel like gaining a superpower.",
    webDevConnection:
      "Every time you memoize a function, index data by ID, or deduplicate a list, you're using a HashMap. This is your most-used DSA tool as a web dev.",
    problemCount: 26,
    status: "locked",
    jsBridgeTopics: [
      "JavaScript's native Map vs. plain objects as hash maps — when to use each",
      "Map methods: .set(), .get(), .has(), .delete(), iteration with .entries()",
      "Object key coercion traps (why using objects as keys in {} fails)",
      "Frequency counting pattern with a Map",
    ],
    coreConcepts: [
      "Hash functions: deterministic key-to-index mapping",
      "Collision handling: chaining vs. open addressing (conceptual)",
      "Amortized O(1) for get/set/has — what 'amortized' means",
      "Two-pass vs. one-pass HashMap pattern",
      "HashMap + array combinations: the 'complement lookup' pattern",
      "Grouping and bucketing with HashMaps",
    ],
  },
  {
    id: 6,
    number: 6,
    title: "Recursion",
    slug: "recursion",
    description:
      "The chapter that breaks most self-taught developers. The goal: build the mental model of the call stack as a physical thing.",
    webDevConnection:
      "Parsing nested JSON, traversing the DOM tree, and rendering recursive React components all use recursive patterns.",
    problemCount: 24,
    status: "locked",
    jsBridgeTopics: [
      "JavaScript's call stack — browser DevTools stack trace as visual aid",
      "Stack overflow: what it looks like in console and why it happens",
      "Default function parameters for base-case initialization",
      "How array destructuring maps to recursive subproblems",
    ],
    coreConcepts: [
      "The two laws: base case + recursive case that moves toward it",
      "Trust the recursion — the 'leap of faith' mental model",
      "Tracing the call stack manually for small inputs",
      "Tail recursion vs. tree recursion — complexity implications",
      "Memoization: caching return values to avoid recomputation",
      "Converting recursion to iteration with an explicit stack",
    ],
  },
  {
    id: 7,
    number: 7,
    title: "Backtracking",
    slug: "backtracking",
    description:
      "The final chapter. Backtracking is recursion with decision-making and undo. Everything from the previous 6 chapters converges here.",
    webDevConnection:
      "Form validation trees, multi-step wizard flows, and game AI all use backtracking. The undo button in any app is a backtracking pattern.",
    problemCount: 21,
    status: "locked",
    jsBridgeTopics: [
      "Array.push() / Array.pop() as the undo mechanism",
      "for...of and index-based loops — when each is needed",
      "Passing arrays by reference vs. spreading for immutable snapshots",
      "Set for O(1) 'have I visited this?' checks",
    ],
    coreConcepts: [
      "The backtracking template: choose → explore → unchoose",
      "The decision tree mental model",
      "Pruning: cutting branches early for performance",
      "State management: mutable push/pop vs. immutable spread",
      "Permutations vs. combinations vs. subsets — three fundamental types",
      "Constraint satisfaction: adding 'is this valid?' checks",
    ],
  },
  {
    id: 8,
    number: 8,
    title: "Strings",
    slug: "strings",
    description:
      "Strings are arrays of characters with their own tricks. Master pattern matching, sliding windows on strings, and the subtle differences between string and array manipulation.",
    webDevConnection:
      "URL parsing, form validation, search highlighting, template engines — strings are everywhere in web dev. Understanding them algorithmically makes you faster.",
    problemCount: 20,
    status: "locked",
    jsBridgeTopics: [
      "Strings are immutable in JS — every 'modification' creates a new string",
      "charCodeAt() and fromCharCode() for character math",
      "String.prototype.split(), join(), slice() — the string toolkit",
      "Template literals and tagged templates for string building",
      "Regular expressions as pattern matching (conceptual, not implementation)",
    ],
    coreConcepts: [
      "String traversal and character frequency counting",
      "Sliding window on strings: finding substrings efficiently",
      "Two-pointer on strings: palindromes and comparisons",
      "Anagram detection and pattern matching",
      "String building: when to use arrays vs. concatenation",
      "Big-O for string operations: concatenation is O(n), not O(1)",
    ],
  },
  {
    id: 9,
    number: 9,
    title: "Linked Lists",
    slug: "linked-lists",
    description:
      "Your first non-contiguous data structure. Linked lists teach pointer manipulation — the mental model transfers directly to trees and graphs.",
    webDevConnection:
      "Browser history (back/forward), undo/redo stacks, and LRU caches all use linked list patterns. React's fiber architecture is a linked list.",
    problemCount: 22,
    status: "locked",
    jsBridgeTopics: [
      "Object references in JS — variables hold references, not values",
      "Creating linked structures with { value, next } objects",
      "The difference between reassigning a variable and mutating an object",
      "Null checks and optional chaining (node?.next)",
      "Garbage collection: what happens when you lose all references to a node",
    ],
    coreConcepts: [
      "Singly vs. doubly linked lists — trade-offs",
      "Traversal: following the next pointer until null",
      "Insertion and deletion at head, tail, and middle — all O(1) with a reference",
      "The runner technique: slow and fast pointers for cycle detection",
      "Reversing a linked list: the three-pointer dance",
      "Dummy head node: simplifying edge cases for insertion/deletion",
    ],
  },
  {
    id: 10,
    number: 10,
    title: "Stacks",
    slug: "stacks",
    description:
      "Last In, First Out. Stacks are deceptively simple but unlock powerful patterns — from expression parsing to monotonic stack tricks used in hard interview problems.",
    webDevConnection:
      "The browser call stack, undo functionality, nested route matching, and bracket validation in code editors all use stacks.",
    problemCount: 18,
    status: "locked",
    jsBridgeTopics: [
      "Array.push() and Array.pop() — arrays as stacks in JS",
      "The call stack: what happens when functions call functions",
      "Stack overflow: the consequence of unbounded recursion",
      "try/catch and the error propagation stack",
    ],
    coreConcepts: [
      "LIFO principle: last in, first out",
      "Stack operations: push O(1), pop O(1), peek O(1)",
      "Balanced parentheses: the classic stack application",
      "Monotonic stack: maintaining sorted order for next-greater/next-smaller problems",
      "Stack-based expression evaluation: infix, postfix, prefix",
      "Using a stack to simulate recursion iteratively",
    ],
  },
  {
    id: 11,
    number: 11,
    title: "Queues",
    slug: "queues",
    description:
      "First In, First Out. Queues power BFS, task scheduling, and every buffer you've ever used. This chapter bridges into graph algorithms.",
    webDevConnection:
      "Event loops, message queues, job schedulers, and request rate limiters — queues are the backbone of async programming.",
    problemCount: 16,
    status: "locked",
    jsBridgeTopics: [
      "Array.push() and Array.shift() — arrays as queues (and why shift is O(n))",
      "JavaScript's event loop and microtask queue",
      "setTimeout / setInterval as queue-based scheduling",
      "Implementing an efficient queue with an object and two pointers",
    ],
    coreConcepts: [
      "FIFO principle: first in, first out",
      "Queue operations: enqueue O(1), dequeue O(1)",
      "Circular queue: reusing space with modulo arithmetic",
      "Deque (double-ended queue): operations at both ends",
      "BFS uses a queue — DFS uses a stack (the fundamental distinction)",
      "Priority queue preview: when FIFO isn't enough",
    ],
  },
  {
    id: 12,
    number: 12,
    title: "Trees",
    slug: "trees",
    description:
      "The most important non-linear data structure. Binary trees, BSTs, and tree traversals form the backbone of countless algorithms and real-world systems.",
    webDevConnection:
      "The DOM is a tree. React's virtual DOM diffing is tree comparison. File systems, JSON parsing, and component hierarchies are all tree problems.",
    problemCount: 28,
    status: "locked",
    jsBridgeTopics: [
      "Recursive object structures: { value, left, right }",
      "Tree construction from nested objects/JSON",
      "Recursion is the natural tool for trees — each subtree is a smaller tree",
      "null as the base case for empty subtrees",
      "Spread operator and destructuring for tree node creation",
    ],
    coreConcepts: [
      "Binary tree terminology: root, leaf, height, depth, level",
      "Three traversals: inorder (left-root-right), preorder (root-left-right), postorder (left-right-root)",
      "Level-order traversal (BFS) with a queue",
      "Binary Search Tree (BST): left < root < right invariant",
      "BST operations: search O(h), insert O(h), delete O(h)",
      "Tree height and balance — why O(log n) vs O(n) matters",
      "Common patterns: DFS with return values, passing state down, building results up",
    ],
  },
  {
    id: 13,
    number: 13,
    title: "Heaps & Priority Queues",
    slug: "heaps",
    description:
      "When you need the minimum or maximum efficiently and repeatedly. Heaps power everything from Dijkstra's algorithm to task schedulers.",
    webDevConnection:
      "Job priority queues, rate limiters with priority, and real-time leaderboards all use heaps. Any 'top K' feature in your app is a heap problem.",
    problemCount: 16,
    status: "locked",
    jsBridgeTopics: [
      "Arrays as binary trees: parent at i, children at 2i+1 and 2i+2",
      "Comparison functions: (a, b) => a - b for min-heap ordering",
      "Class syntax for implementing a MinHeap/MaxHeap",
      "Destructuring swap: [a, b] = [b, a]",
    ],
    coreConcepts: [
      "Complete binary tree property: filled level by level",
      "Min-heap vs. max-heap: parent is always smaller/larger than children",
      "Heapify up (bubble up) and heapify down (sink down)",
      "Insert O(log n), extract-min/max O(log n), peek O(1)",
      "Building a heap from an array: O(n) bottom-up heapify",
      "Top-K pattern: maintain a heap of size K for streaming data",
    ],
  },
  {
    id: 14,
    number: 14,
    title: "Graphs",
    slug: "graphs",
    description:
      "The ultimate general-purpose data structure. Every relationship, network, and connection problem is a graph problem. Master BFS, DFS, and shortest paths.",
    webDevConnection:
      "Social networks (friends-of-friends), dependency resolution (npm install), route planning, and recommendation engines are all graph algorithms.",
    problemCount: 24,
    status: "locked",
    jsBridgeTopics: [
      "Adjacency list with Map<string, string[]> — the standard JS graph representation",
      "Set for visited tracking — O(1) lookup",
      "Recursion for DFS, queue (array) for BFS",
      "Object/Map for storing distances and parent pointers",
      "Iterating over Map entries with for...of",
    ],
    coreConcepts: [
      "Graph terminology: vertices, edges, directed vs. undirected, weighted vs. unweighted",
      "Representations: adjacency list vs. adjacency matrix — trade-offs",
      "DFS: go deep first, use a stack (or recursion) — good for paths 'and cycles",
      "BFS: go wide first, use a queue — guarantees shortest path in unweighted graphs",
      "Cycle detection in directed and undirected graphs",
      "Topological sort: ordering tasks with dependencies",
      "Shortest path: BFS for unweighted, Dijkstra for weighted",
    ],
  },
  {
    id: 15,
    number: 15,
    title: "Dynamic Programming",
    slug: "dynamic-programming",
    description:
      "The chapter that separates good from great. DP is just recursion + memoization, but recognizing the pattern takes practice. Start with the basics and build intuition.",
    webDevConnection:
      "Diff algorithms (like React's reconciliation), text editors (edit distance for spell check), and layout engines (line breaking) all use DP.",
    problemCount: 26,
    status: "locked",
    jsBridgeTopics: [
      "Closures and memoization with Map/object caches",
      "Array.fill() and Array.from() for initializing DP tables",
      "Nested loops for 2D DP tables",
      "Ternary operator for min/max decisions",
      "BigInt for problems with large intermediate values",
    ],
    coreConcepts: [
      "Overlapping subproblems: the same computation happens multiple times",
      "Optimal substructure: the optimal solution contains optimal sub-solutions",
      "Top-down (memoization): recursion + cache",
      "Bottom-up (tabulation): iterative table filling",
      "State definition: what variables define a unique subproblem?",
      "Transition: how does the current state relate to previous states?",
      "Space optimization: rolling arrays when you only need the previous row",
      "Classic patterns: Fibonacci, knapsack, LCS, LIS, coin change, grid paths",
    ],
  },
  {
    id: 16,
    number: 16,
    title: "Greedy Algorithms",
    slug: "greedy",
    description:
      "Make the locally optimal choice at each step and hope it leads to the global optimum. Greedy works when it works — the skill is recognizing when.",
    webDevConnection:
      "Huffman coding (compression), task scheduling in CI/CD pipelines, and cache eviction policies (LRU) are all greedy algorithms.",
    problemCount: 16,
    status: "locked",
    jsBridgeTopics: [
      "Array.sort() with custom comparators for greedy ordering",
      "Destructuring in sort comparators: ([a1, a2], [b1, b2]) =>",
      "Reduce for accumulating greedy choices",
      "Math.max() and Math.min() for local optimal decisions",
    ],
    coreConcepts: [
      "Greedy choice property: a local optimum leads to a global optimum",
      "Activity selection / interval scheduling: sort by end time",
      "Fractional knapsack: take the best value-to-weight ratio first",
      "Huffman coding: build optimal prefix codes with a priority queue",
      "When greedy fails: coin change with arbitrary denominations",
      "Proving greedy works: exchange argument and staying ahead",
    ],
  },
  {
    id: 17,
    number: 17,
    title: "Tries",
    slug: "tries",
    description:
      "The prefix tree — purpose-built for string search. Autocomplete, spell checkers, and IP routing tables all rely on this elegant structure.",
    webDevConnection:
      "Autocomplete search bars, URL routers (like Next.js routing), command palettes, and dictionary lookups all use trie-like structures.",
    problemCount: 12,
    status: "locked",
    jsBridgeTopics: [
      "Nested objects as tree nodes: { children: {}, isEnd: false }",
      "Dynamic property access: node.children[char]",
      "Iterating over characters with for...of on strings",
      "Optional chaining for safe traversal: node?.children?.[char]",
    ],
    coreConcepts: [
      "Trie structure: each node represents a character, paths form words",
      "Insert, search, and startsWith operations — all O(word length)",
      "Space trade-off: tries use more memory but enable prefix queries",
      "Prefix matching: find all words starting with a given prefix",
      "Trie vs. HashMap for dictionary problems — when each wins",
      "Wildcard search: using DFS with '.' matching any character",
    ],
  },
  {
    id: 18,
    number: 18,
    title: "Bit Manipulation",
    slug: "bit-manipulation",
    description:
      "Think in binary. Bit manipulation gives you O(1) tricks that feel like magic — toggling, checking, and counting bits to solve problems with zero extra space.",
    webDevConnection:
      "Feature flags, permission systems (Unix file permissions), color manipulation (RGB hex), and protocol parsing all use bitwise operations.",
    problemCount: 14,
    status: "locked",
    jsBridgeTopics: [
      "Bitwise operators: & (AND), | (OR), ^ (XOR), ~ (NOT), << (left shift), >> (right shift)",
      "Number.toString(2) to visualize binary representation",
      "parseInt('1010', 2) to convert binary strings to numbers",
      "JavaScript uses 32-bit integers for bitwise operations",
    ],
    coreConcepts: [
      "AND, OR, XOR, NOT — truth tables and intuition",
      "XOR tricks: a ^ a = 0, a ^ 0 = a — finding the single unique element",
      "Bit masking: checking, setting, and clearing specific bits",
      "Counting set bits (Hamming weight) and Hamming distance",
      "Power of two check: n & (n-1) === 0",
      "Bit shifting for multiplication/division by powers of 2",
    ],
  },
];
